import { PinyinElement, ZhuyinSymbol, ToneInfo } from "../types";

export const INITIALS: readonly PinyinElement[] = [
  // 입술소리 (순음 唇音)
  {
    id: "init-1",
    type: "INITIAL",
    symbol: "b",
    zhuyin: "ㄅ",
    ipa: "[p]",
    koreanGuide: "쌍비읍(ㅃ) 또는 둔탁한 비읍(ㅂ)",
    description: "두 입술을 다물었다가 떼며 성대를 울리지 않고 내는 무기음 (b)",
    exampleHanzi: "爸",
    examplePinyin: "bà",
    exampleMeaning: "아빠",
  },
  {
    id: "init-2",
    type: "INITIAL",
    symbol: "p",
    zhuyin: "ㄆ",
    ipa: "[pʰ]",
    koreanGuide: "거센 피읖(ㅍ)",
    description: "두 입술을 다물었다가 강하게 거센 숨을 뱉으며 내는 유기음 (p)",
    exampleHanzi: "朋",
    examplePinyin: "péng",
    exampleMeaning: "친구",
  },
  {
    id: "init-3",
    type: "INITIAL",
    symbol: "m",
    zhuyin: "ㄇ",
    ipa: "[m]",
    koreanGuide: "미음(ㅁ)",
    description: "두 입술을 붙이고 코로 공기를 보내며 내는 비음 (m)",
    exampleHanzi: "妈",
    examplePinyin: "mā",
    exampleMeaning: "엄마",
  },
  {
    id: "init-4",
    type: "INITIAL",
    symbol: "f",
    zhuyin: "ㄈ",
    ipa: "[f]",
    koreanGuide: "영어 F 발음",
    description: "윗이빨로 아랫입술을 살짝 누르고 틈 사이로 내는 순치 마찰음 (f)",
    exampleHanzi: "飞",
    examplePinyin: "fēi",
    exampleMeaning: "날다",
  },

  // 혓바닥 끝소리 (설첨음 舌尖音)
  {
    id: "init-5",
    type: "INITIAL",
    symbol: "d",
    zhuyin: "ㄉ",
    ipa: "[t]",
    koreanGuide: "쌍디귿(ㄸ) 또는 둔탁한 디귿(ㄷ)",
    description: "혀끝을 윗잇몸에 대었다 떼며 숨을 거의 뱉지 않는 소리 (d)",
    exampleHanzi: "大",
    examplePinyin: "dà",
    exampleMeaning: "크다",
  },
  {
    id: "init-6",
    type: "INITIAL",
    symbol: "t",
    zhuyin: "ㄊ",
    ipa: "[tʰ]",
    koreanGuide: "거센 티읕(ㅌ)",
    description: "혀끝을 윗잇몸에 대었다 떼며 거센 숨을 힘차게 뿜는 소리 (t)",
    exampleHanzi: "他",
    examplePinyin: "tā",
    exampleMeaning: "그",
  },
  {
    id: "init-7",
    type: "INITIAL",
    symbol: "n",
    zhuyin: "ㄋ",
    ipa: "[n]",
    koreanGuide: "니은(ㄴ)",
    description: "혀끝을 윗잇몸에 붙이고 코를 울려 내는 비음 (n)",
    exampleHanzi: "你",
    examplePinyin: "nǐ",
    exampleMeaning: "너",
  },
  {
    id: "init-8",
    type: "INITIAL",
    symbol: "l",
    zhuyin: "ㄌ",
    ipa: "[l]",
    koreanGuide: "리을(ㄹ)",
    description: "혀끝을 윗잇몸에 대고 양옆으로 공기를 흘려보내는 설측음 (l)",
    exampleHanzi: "来",
    examplePinyin: "lái",
    exampleMeaning: "오다",
  },

  // 혀뿌리소리 (설근음 舌根音)
  {
    id: "init-9",
    type: "INITIAL",
    symbol: "g",
    zhuyin: "ㄍ",
    ipa: "[k]",
    koreanGuide: "쌍기역(ㄲ) 또는 둔탁한 기역(ㄱ)",
    description: "혀 뒤쪽을 목구멍 쪽 여린입천장에 닿았다 떼며 내는 무기음 (g)",
    exampleHanzi: "个",
    examplePinyin: "gè",
    exampleMeaning: "개(양사)",
  },
  {
    id: "init-10",
    type: "INITIAL",
    symbol: "k",
    zhuyin: "ㄎ",
    ipa: "[kʰ]",
    koreanGuide: "거센 키읔(ㅋ)",
    description: "혀 뒤쪽을 여린입천장에 닿았다 떼며 거세게 숨을 뿜는 유기음 (k)",
    exampleHanzi: "看",
    examplePinyin: "kàn",
    exampleMeaning: "보다",
  },
  {
    id: "init-11",
    type: "INITIAL",
    symbol: "h",
    zhuyin: "ㄏ",
    ipa: "[x]",
    koreanGuide: "목 안쪽에서 긁어내는 흐(ㅎ)",
    description: "목구멍 안쪽에서 가볍게 긁으며 공기를 마찰시키는 소리 (h)",
    exampleHanzi: "好",
    examplePinyin: "hǎo",
    exampleMeaning: "좋다",
  },

  // 혓바닥 앞소리 (설면음 舌面音)
  {
    id: "init-12",
    type: "INITIAL",
    symbol: "j",
    zhuyin: "ㄐ",
    ipa: "[tɕ]",
    koreanGuide: "쌍지읒(ㅉ) 또는 지읒(ㅈ)",
    description: "혓바닥 앞부분을 센입천장에 붙였다 떼며 숨을 거의 뱉지 않는 소리 (j)",
    exampleHanzi: "家",
    examplePinyin: "jiā",
    exampleMeaning: "집",
  },
  {
    id: "init-13",
    type: "INITIAL",
    symbol: "q",
    zhuyin: "ㄑ",
    ipa: "[tɕʰ]",
    koreanGuide: "거센 치읓(ㅊ)",
    description: "혓바닥 앞부분을 센입천장에 붙였다 떼며 거센 숨을 뿜는 소리 (q)",
    exampleHanzi: "去",
    examplePinyin: "qù",
    exampleMeaning: "가다",
  },
  {
    id: "init-14",
    type: "INITIAL",
    symbol: "x",
    zhuyin: "ㄒ",
    ipa: "[ɕ]",
    koreanGuide: "시/쉬(ㅅ)",
    description: "혓바닥 앞부분을 센입천장에 가까이 대고 틈 사이로 마찰시키는 소리 (x)",
    exampleHanzi: "谢",
    examplePinyin: "xiè",
    exampleMeaning: "감사하다",
  },

  // 혀말이소리 (권설음 卷舌音)
  {
    id: "init-15",
    type: "INITIAL",
    symbol: "zh",
    zhuyin: "ㄓ",
    ipa: "[tʂ]",
    koreanGuide: "혀를 말아올려 내는 쯔/쯧",
    description: "혀끝을 입천장 뒤쪽으로 말아올려 닿았다 떼며 내는 무기음 (zh)",
    exampleHanzi: "中",
    examplePinyin: "zhōng",
    exampleMeaning: "가운데",
  },
  {
    id: "init-16",
    type: "INITIAL",
    symbol: "ch",
    zhuyin: "ㄔ",
    ipa: "[tʂʰ]",
    koreanGuide: "혀를 말아올려 거세게 내는 츠/츳",
    description: "혀끝을 말아올려 닿았다 떼며 거센 숨을 힘차게 뿜는 유기음 (ch)",
    exampleHanzi: "吃",
    examplePinyin: "chī",
    exampleMeaning: "먹다",
  },
  {
    id: "init-17",
    type: "INITIAL",
    symbol: "sh",
    zhuyin: "ㄕ",
    ipa: "[ʂ]",
    koreanGuide: "혀를 말아올려 내는 스/쉬",
    description: "혀끝을 말아올려 입천장과의 좁은 틈 사이로 공기를 마찰시키는 소리 (sh)",
    exampleHanzi: "是",
    examplePinyin: "shì",
    exampleMeaning: "~이다",
  },
  {
    id: "init-18",
    type: "INITIAL",
    symbol: "r",
    zhuyin: "ㄖ",
    ipa: "[ʐ]",
    koreanGuide: "혀를 말아올려 성대를 울리는 르",
    description: "혀끝을 말아올려 입천장 틈으로 공기를 내보내며 성대를 울리는 유성 마찰음 (r)",
    exampleHanzi: "人",
    examplePinyin: "rén",
    exampleMeaning: "사람",
  },

  // 혀치조음 (설치음 舌齿音)
  {
    id: "init-19",
    type: "INITIAL",
    symbol: "z",
    zhuyin: "ㄗ",
    ipa: "[ts]",
    koreanGuide: "윗니 뒤쪽에 혀를 대고 내는 쯔",
    description: "혀끝을 윗니 뒤쪽에 대었다 떼며 숨을 거의 내뱉지 않는 무기음 (z)",
    exampleHanzi: "在",
    examplePinyin: "zài",
    exampleMeaning: "있다/에서",
  },
  {
    id: "init-20",
    type: "INITIAL",
    symbol: "c",
    zhuyin: "ㄘ",
    ipa: "[tsʰ]",
    koreanGuide: "윗니 뒤쪽에 혀를 대고 거세게 내는 츠",
    description: "혀끝을 윗니 뒤쪽에 대었다 떼며 거센 숨을 뿜는 유기음 (c)",
    exampleHanzi: "菜",
    examplePinyin: "cài",
    exampleMeaning: "요리/채소",
  },
  {
    id: "init-21",
    type: "INITIAL",
    symbol: "s",
    zhuyin: "ㄙ",
    ipa: "[s]",
    koreanGuide: "윗니 뒤쪽에 혀를 대고 내는 스",
    description: "혀끝을 윗니 뒤쪽에 가까이 대고 틈 사이로 공기를 마찰시키는 소리 (s)",
    exampleHanzi: "三",
    examplePinyin: "sān",
    exampleMeaning: "셋(3)",
  },
] as const;

export const FINALS: readonly PinyinElement[] = [
  // 기본 단운모 (单韵母)
  {
    id: "final-1",
    type: "FINAL",
    symbol: "a",
    zhuyin: "ㄚ",
    ipa: "[a]",
    koreanGuide: "아",
    description: "입을 크게 벌리고 목구멍을 열어 자연스럽게 내는 소리 (a)",
    exampleHanzi: "大",
    examplePinyin: "dà",
    exampleMeaning: "크다",
  },
  {
    id: "final-2",
    type: "FINAL",
    symbol: "o",
    zhuyin: "ㄛ",
    ipa: "[o]",
    koreanGuide: "오 (어와 오의 중간)",
    description: "입술을 동그랗게 모으고 혀를 뒤로 당기며 내는 소리 (o)",
    exampleHanzi: "我",
    examplePinyin: "wǒ",
    exampleMeaning: "나",
  },
  {
    id: "final-3",
    type: "FINAL",
    symbol: "e",
    zhuyin: "ㄜ",
    ipa: "[ɤ]",
    koreanGuide: "으어",
    description: "입을 멍하게 벌린 상태에서 목 안쪽에서 깊게 내는 소리 (e)",
    exampleHanzi: "喝",
    examplePinyin: "hē",
    exampleMeaning: "마시다",
  },
  {
    id: "final-4",
    type: "MEDIAL",
    symbol: "i",
    zhuyin: "ㄧ",
    ipa: "[i]",
    koreanGuide: "이",
    description: "입술을 양옆으로 넓게 벌리고 편평하게 미소 지으며 내는 소리 (i)",
    exampleHanzi: "你",
    examplePinyin: "nǐ",
    exampleMeaning: "너",
  },
  {
    id: "final-5",
    type: "MEDIAL",
    symbol: "u",
    zhuyin: "ㄨ",
    ipa: "[u]",
    koreanGuide: "우",
    description: "입술을 뾰족하게 동그랗게 앞으로 내밀며 내는 소리 (u)",
    exampleHanzi: "不",
    examplePinyin: "bù",
    exampleMeaning: "아니다",
  },
  {
    id: "final-6",
    type: "MEDIAL",
    symbol: "v",
    zhuyin: "ㄩ",
    ipa: "[y]",
    koreanGuide: "위 (입모양 고정)",
    description: "입술을 둥글게 오므린 채 모양을 전혀 바꾸지 않고 내는 소리 (ü/v)",
    exampleHanzi: "去",
    examplePinyin: "qù",
    exampleMeaning: "가다",
  },
  {
    id: "final-7",
    type: "FINAL",
    symbol: "ai",
    zhuyin: "ㄞ",
    ipa: "[ai]",
    koreanGuide: "아이",
    description: "아(a)에서 시작해 이(i)로 부드럽게 이어지는 복운모 (ai)",
    exampleHanzi: "来",
    examplePinyin: "lái",
    exampleMeaning: "오다",
  },
  {
    id: "final-8",
    type: "FINAL",
    symbol: "ei",
    zhuyin: "ㄟ",
    ipa: "[ei]",
    koreanGuide: "에이",
    description: "에(e)에서 이(i)로 부드럽게 미끄러지듯 내는 복운모 (ei)",
    exampleHanzi: "飞",
    examplePinyin: "fēi",
    exampleMeaning: "날다",
  },
  {
    id: "final-9",
    type: "FINAL",
    symbol: "ao",
    zhuyin: "ㄠ",
    ipa: "[au]",
    koreanGuide: "아오",
    description: "아(a)에서 오(o)로 입을 둥글게 모으며 내는 복운모 (ao)",
    exampleHanzi: "好",
    examplePinyin: "hǎo",
    exampleMeaning: "좋다",
  },
  {
    id: "final-10",
    type: "FINAL",
    symbol: "ou",
    zhuyin: "ㄡ",
    ipa: "[ou]",
    koreanGuide: "오우",
    description: "오(o)에서 우(u)로 작아지듯 내는 복운모 (ou)",
    exampleHanzi: "有",
    examplePinyin: "yǒu",
    exampleMeaning: "있다",
  },
  {
    id: "final-11",
    type: "FINAL",
    symbol: "an",
    zhuyin: "ㄢ",
    ipa: "[an]",
    koreanGuide: "안",
    description: "아(a) 발음 후 혀끝을 윗잇몸에 붙이며 내는 앞비음 (an)",
    exampleHanzi: "三",
    examplePinyin: "sān",
    exampleMeaning: "셋",
  },
  {
    id: "final-12",
    type: "FINAL",
    symbol: "en",
    zhuyin: "ㄣ",
    ipa: "[ən]",
    koreanGuide: "언/은",
    description: "으어(e) 발음 후 혀끝을 윗잇몸에 붙이며 코로 내는 비음 (en)",
    exampleHanzi: "很",
    examplePinyin: "hěn",
    exampleMeaning: "매우",
  },
  {
    id: "final-13",
    type: "FINAL",
    symbol: "ang",
    zhuyin: "ㄤ",
    ipa: "[aŋ]",
    koreanGuide: "앙 (울림)",
    description: "아(a) 발음 후 혀뿌리를 들어 목젖 쪽을 막으며 내는 뒷비음 (ang)",
    exampleHanzi: "忙",
    examplePinyin: "máng",
    exampleMeaning: "바쁘다",
  },
  {
    id: "final-14",
    type: "FINAL",
    symbol: "eng",
    zhuyin: "ㄥ",
    ipa: "[əŋ]",
    koreanGuide: "엉/응",
    description: "으(e) 발음 후 혀뿌리를 들어 목구멍 쪽을 막으며 울리는 비음 (eng)",
    exampleHanzi: "朋",
    examplePinyin: "péng",
    exampleMeaning: "벗/친구",
  },
  {
    id: "final-15",
    type: "FINAL",
    symbol: "er",
    zhuyin: "ㄦ",
    ipa: "[aɚ]",
    koreanGuide: "얼 (혀 말기)",
    description: "혀를 입천장 가운데로 말아올리며 내는 권설모음 (er)",
    exampleHanzi: "二",
    examplePinyin: "èr",
    exampleMeaning: "둘",
  },
] as const;

export const ALL_ZHUYIN_SYMBOLS: readonly ZhuyinSymbol[] = [
  // 21 Initials
  { id: "z-b", symbol: "ㄅ", name: "보", category: "INITIAL", pinyin: "b", ipa: "[p]", koreanGuide: "ㅂ/ㅃ", description: "두 입술을 뗐다 붙이며 내는 소리", exampleWord: "爸爸", exampleMeaning: "아빠" },
  { id: "z-p", symbol: "ㄆ", name: "포", category: "INITIAL", pinyin: "p", ipa: "[pʰ]", koreanGuide: "ㅍ", description: "두 입술에서 거세게 터뜨리는 소리", exampleWord: "朋友", exampleMeaning: "친구" },
  { id: "z-m", symbol: "ㄇ", name: "모", category: "INITIAL", pinyin: "m", ipa: "[m]", koreanGuide: "ㅁ", description: "두 입술을 다물고 코로 내는 콧소리", exampleWord: "妈妈", exampleMeaning: "엄마" },
  { id: "z-f", symbol: "ㄈ", name: "포", category: "INITIAL", pinyin: "f", ipa: "[f]", koreanGuide: "F", description: "윗니로 아랫입술을 스치는 소리", exampleWord: "飞机", exampleMeaning: "비행기" },
  { id: "z-d", symbol: "ㄉ", name: "더", category: "INITIAL", pinyin: "d", ipa: "[t]", koreanGuide: "ㄷ/ㄸ", description: "혀끝을 윗잇몸에 닿았다 떼는 소리", exampleWord: "大", exampleMeaning: "크다" },
  { id: "z-t", symbol: "ㄊ", name: "터", category: "INITIAL", pinyin: "t", ipa: "[tʰ]", koreanGuide: "ㅌ", description: "혀끝에서 거세게 터져 나오는 소리", exampleWord: "他", exampleMeaning: "그" },
  { id: "z-n", symbol: "ㄋ", name: "너", category: "INITIAL", pinyin: "n", ipa: "[n]", koreanGuide: "ㄴ", description: "혀끝을 윗잇몸에 대고 내는 콧소리", exampleWord: "你", exampleMeaning: "너" },
  { id: "z-l", symbol: "ㄌ", name: "러", category: "INITIAL", pinyin: "l", ipa: "[l]", koreanGuide: "ㄹ", description: "혀끝 양옆으로 공기를 보내는 소리", exampleWord: "来", exampleMeaning: "오다" },
  { id: "z-g", symbol: "ㄍ", name: "거", category: "INITIAL", pinyin: "g", ipa: "[k]", koreanGuide: "ㄱ/ㄲ", description: "혀뿌리로 여린입천장을 막았다 떼는 소리", exampleWord: "哥哥", exampleMeaning: "형/오빠" },
  { id: "z-k", symbol: "ㄎ", name: "커", category: "INITIAL", pinyin: "k", ipa: "[kʰ]", koreanGuide: "ㅋ", description: "혀뿌리에서 거세게 터뜨리는 소리", exampleWord: "看", exampleMeaning: "보다" },
  { id: "z-h", symbol: "ㄏ", name: "허", category: "INITIAL", pinyin: "h", ipa: "[x]", koreanGuide: "ㅎ", description: "목구멍 쪽에서 긁어내는 마찰음", exampleWord: "好", exampleMeaning: "좋다" },
  { id: "z-j", symbol: "ㄐ", name: "지", category: "INITIAL", pinyin: "j", ipa: "[tɕ]", koreanGuide: "ㅈ/ㅉ", description: "혓바닥을 센입천장에 대고 내는 소리", exampleWord: "家", exampleMeaning: "집" },
  { id: "z-q", symbol: "ㄑ", name: "치", category: "INITIAL", pinyin: "q", ipa: "[tɕʰ]", koreanGuide: "ㅊ", description: "혓바닥에서 거세게 터져 나오는 소리", exampleWord: "去", exampleMeaning: "가다" },
  { id: "z-x", symbol: "ㄒ", name: "시", category: "INITIAL", pinyin: "x", ipa: "[ɕ]", koreanGuide: "ㅅ/ㅆ", description: "혓바닥과 센입천장 틈으로 내는 소리", exampleWord: "谢谢", exampleMeaning: "감사하다" },
  { id: "z-zh", symbol: "ㄓ", name: "즈(권설)", category: "INITIAL", pinyin: "zh", ipa: "[tʂ]", koreanGuide: "혀말은 ㅉ", description: "혀끝을 말아올려 천장에 대었다 떼는 소리", exampleWord: "中国", exampleMeaning: "중국" },
  { id: "z-ch", symbol: "ㄔ", name: "츠(권설)", category: "INITIAL", pinyin: "ch", ipa: "[tʂʰ]", koreanGuide: "혀말은 ㅊ", description: "혀끝을 말아올려 거세게 내뿜는 소리", exampleWord: "吃饭", exampleMeaning: "밥을 먹다" },
  { id: "z-sh", symbol: "ㄕ", name: "스(권설)", category: "INITIAL", pinyin: "sh", ipa: "[ʂ]", koreanGuide: "혀말은 ㅅ", description: "혀끝을 말아올려 틈 사이로 마찰시키는 소리", exampleWord: "是", exampleMeaning: "~이다" },
  { id: "z-r", symbol: "ㄖ", name: "르(권설)", category: "INITIAL", pinyin: "r", ipa: "[ʐ]", koreanGuide: "혀말은 ㄹ", description: "혀끝을 말아올려 성대를 울리는 소리", exampleWord: "人", exampleMeaning: "사람" },
  { id: "z-z", symbol: "ㄗ", name: "즈(치조)", category: "INITIAL", pinyin: "z", ipa: "[ts]", koreanGuide: "평평한 ㅉ", description: "혀끝을 윗니 뒤에 대었다 떼는 소리", exampleWord: "在", exampleMeaning: "있다" },
  { id: "z-c", symbol: "ㄘ", name: "츠(치조)", category: "INITIAL", pinyin: "c", ipa: "[tsʰ]", koreanGuide: "평평한 ㅊ", description: "혀끝을 윗니 뒤에서 거세게 터뜨리는 소리", exampleWord: "菜", exampleMeaning: "요리" },
  { id: "z-s", symbol: "ㄙ", name: "스(치조)", category: "INITIAL", pinyin: "s", ipa: "[s]", koreanGuide: "평평한 ㅅ", description: "혀끝을 윗니 뒤 틈으로 마찰시키는 소리", exampleWord: "三", exampleMeaning: "셋" },

  // 3 Medials (개음)
  { id: "z-i", symbol: "ㄧ", name: "이", category: "MEDIAL", pinyin: "i / y", ipa: "[i]", koreanGuide: "이", description: "입을 옆으로 펴며 내는 맑은 소리", exampleWord: "一", exampleMeaning: "하나" },
  { id: "z-u", symbol: "ㄨ", name: "우", category: "MEDIAL", pinyin: "u / w", ipa: "[u]", koreanGuide: "우", description: "입술을 둥글게 모으며 내는 소리", exampleWord: "五", exampleMeaning: "다섯" },
  { id: "z-yu", symbol: "ㄩ", name: "위", category: "MEDIAL", pinyin: "ü / yu", ipa: "[y]", koreanGuide: "위 (고정)", description: "입술 모양을 바꾸지 않고 내는 소리", exampleWord: "雨", exampleMeaning: "비" },

  // 13 Finals (운모)
  { id: "z-a", symbol: "ㄚ", name: "아", category: "FINAL", pinyin: "a", ipa: "[a]", koreanGuide: "아", description: "입을 크게 벌리고 시원하게 내는 소리", exampleWord: "他", exampleMeaning: "그" },
  { id: "z-o", symbol: "ㄛ", name: "오", category: "FINAL", pinyin: "o", ipa: "[o]", koreanGuide: "오", description: "입술을 동그랗게 모으며 내는 소리", exampleWord: "波", exampleMeaning: "물결" },
  { id: "z-e", symbol: "ㄜ", name: "으어", category: "FINAL", pinyin: "e", ipa: "[ɤ]", koreanGuide: "으어", description: "목 안쪽에서 멍하게 내는 소리", exampleWord: "喝", exampleMeaning: "마시다" },
  { id: "z-eh", symbol: "ㄝ", name: "에", category: "FINAL", pinyin: "ie / üe (ê)", ipa: "[ɛ]", koreanGuide: "에", description: "입을 약간 벌려 미소 짓듯 내는 소리", exampleWord: "写", exampleMeaning: "쓰다" },
  { id: "z-ai", symbol: "ㄞ", name: "아이", category: "FINAL", pinyin: "ai", ipa: "[ai]", koreanGuide: "아이", description: "아에서 이로 이어지는 소리", exampleWord: "爱", exampleMeaning: "사랑하다" },
  { id: "z-ei", symbol: "ㄟ", name: "에이", category: "FINAL", pinyin: "ei", ipa: "[ei]", koreanGuide: "에이", description: "에에서 이로 미끄러지는 소리", exampleWord: "妹", exampleMeaning: "여동생" },
  { id: "z-ao", symbol: "ㄠ", name: "아오", category: "FINAL", pinyin: "ao", ipa: "[au]", koreanGuide: "아오", description: "아에서 오로 둥글어지는 소리", exampleWord: "高", exampleMeaning: "높다" },
  { id: "z-ou", symbol: "ㄡ", name: "오우", category: "FINAL", pinyin: "ou", ipa: "[ou]", koreanGuide: "오우", description: "오에서 우로 작아지는 소리", exampleWord: "狗", exampleMeaning: "개" },
  { id: "z-an", symbol: "ㄢ", name: "안", category: "FINAL", pinyin: "an", ipa: "[an]", koreanGuide: "안", description: "혀끝으로 입천장을 막는 콧소리", exampleWord: "看", exampleMeaning: "보다" },
  { id: "z-en", symbol: "ㄣ", name: "언/은", category: "FINAL", pinyin: "en", ipa: "[ən]", koreanGuide: "언", description: "으에서 ㄴ으로 끝맺는 콧소리", exampleWord: "门", exampleMeaning: "문" },
  { id: "z-ang", symbol: "ㄤ", name: "앙", category: "FINAL", pinyin: "ang", ipa: "[aŋ]", koreanGuide: "앙", description: "목젖 쪽에서 깊게 울리는 콧소리", exampleWord: "棒", exampleMeaning: "훌륭하다" },
  { id: "z-eng", symbol: "ㄥ", name: "엉/응", category: "FINAL", pinyin: "eng", ipa: "[əŋ]", koreanGuide: "엉", description: "목구멍을 막으며 울리는 콧소리", exampleWord: "风", exampleMeaning: "바람" },
  { id: "z-er", symbol: "ㄦ", name: "얼", category: "FINAL", pinyin: "er", ipa: "[aɚ]", koreanGuide: "얼", description: "혀끝을 입천장 쪽으로 말며 내는 소리", exampleWord: "儿子", exampleMeaning: "아들" },
] as const;

export const TONE_DETAILS: readonly ToneInfo[] = [
  {
    tone: 1,
    name: "1성 (음평 阴平)",
    chineseName: "第一声",
    pinyinMark: "¯ (ā, ō, ē, ī, ū, ǖ)",
    zhuyinMark: "기호 없음 (또는 ˉ)",
    pitchDescription: "높고 평평하게 5-5 높이 유지 (솔음 솔~)",
    pitchContour: [1.0, 1.0, 1.0, 1.0, 1.0],
    audioTip: "도레미파솔~ '솔' 음높이에서 음을 흔들림 없이 길게 유지하세요.",
  },
  {
    tone: 2,
    name: "2성 (양평 阳平)",
    chineseName: "第二声",
    pinyinMark: "ˊ (á, ó, é, í, ú, ǘ)",
    zhuyinMark: "ˊ",
    pitchDescription: "중간에서 높은 음으로 빠르게 상승 (3-5 '네?')",
    pitchContour: [0.3, 0.45, 0.65, 0.85, 1.0],
    audioTip: "의문을 품고 '네? 뭐라고요?' 할 때처럼 소리를 쭉 올려줍니다.",
  },
  {
    tone: 3,
    name: "3성 (상성 上声)",
    chineseName: "第三声",
    pinyinMark: "ˇ (ǎ, ǒ, ě, ǐ, ǔ, ǚ)",
    zhuyinMark: "ˇ",
    pitchDescription: "낮게 떨어졌다가 살짝 올라감 (2-1-4 '아하!')",
    pitchContour: [0.4, 0.15, 0.0, 0.35, 0.6],
    audioTip: "목에 힘을 빼고 가장 낮은 저음까지 푹 내렸다가 끝을 살짝 띄웁니다.",
  },
  {
    tone: 4,
    name: "4성 (거성 去声)",
    chineseName: "第四声",
    pinyinMark: "ˋ (à, ò, è, ì, ù, ǜ)",
    zhuyinMark: "ˋ",
    pitchDescription: "높은 음에서 가장 낮은 음으로 강하게 내리꽂음 (5-1 '앗!')",
    pitchContour: [1.0, 0.75, 0.45, 0.2, 0.0],
    audioTip: "위에서 아래로 도끼를 내리찍듯 짧고 단호하게 뚝 떨어뜨립니다.",
  },
  {
    tone: 5,
    name: "경성 (경성 轻声)",
    chineseName: "轻声",
    pinyinMark: "• (기호 없음 a, o, e)",
    zhuyinMark: "˙",
    pitchDescription: "성조를 잃고 가볍고 짧게 툭 던지는 소리",
    pitchContour: [0.5, 0.4, 0.3],
    audioTip: "힘을 완전히 빼고 짧게 톡 얹어주는 느낌으로 소리 냅니다.",
  },
] as const;

