import { Word } from "../types";

export const INITIAL_WORDS: readonly Word[] = [
  {
    id: "w-1",
    pinyin: "mā",
    pinyinNumeric: "ma1",
    hanzi: "妈",
    meaning: "엄마",
    tone: 1,
    level: 1,
  },
  {
    id: "w-2",
    pinyin: "má",
    pinyinNumeric: "ma2",
    hanzi: "麻",
    meaning: "삼(베)",
    tone: 2,
    level: 1,
  },
  {
    id: "w-3",
    pinyin: "mǎ",
    pinyinNumeric: "ma3",
    hanzi: "马",
    meaning: "말",
    tone: 3,
    level: 1,
  },
  {
    id: "w-4",
    pinyin: "mà",
    pinyinNumeric: "ma4",
    hanzi: "骂",
    meaning: "욕하다",
    tone: 4,
    level: 1,
  },
  {
    id: "w-5",
    pinyin: "ma",
    pinyinNumeric: "ma5",
    hanzi: "吗",
    meaning: "입력 의문 조사 (~입니까?)",
    tone: 5,
    level: 1,
  },

  // 기초 인사 및 핵심 단어
  {
    id: "w-6",
    pinyin: "nǐ",
    pinyinNumeric: "ni3",
    hanzi: "你",
    meaning: "너",
    tone: 3,
    level: 1,
  },
  {
    id: "w-7",
    pinyin: "hǎo",
    pinyinNumeric: "hao3",
    hanzi: "好",
    meaning: "좋다",
    tone: 3,
    level: 1,
  },
  {
    id: "w-8",
    pinyin: "wǒ",
    pinyinNumeric: "wo3",
    hanzi: "我",
    meaning: "나",
    tone: 3,
    level: 1,
  },
  {
    id: "w-9",
    pinyin: "tā",
    pinyinNumeric: "ta1",
    hanzi: "他",
    meaning: "그 (그 사람)",
    tone: 1,
    level: 1,
  },
  {
    id: "w-10",
    pinyin: "bù",
    pinyinNumeric: "bu4",
    hanzi: "不",
    meaning: "아니다",
    tone: 4,
    level: 1,
  },
] as const;
