import { Word } from "../types";

export const INITIAL_WORDS: readonly Word[] = [
  // 1~4성 & 경성 마(ma) 패밀리
  {
    id: "w-1",
    pinyin: "mā",
    pinyinNumeric: "ma1",
    zhuyin: "ㄇㄚ",
    hanzi: "妈",
    meaning: "엄마",
    tone: 1,
    level: 1,
    category: "family",
    rules: ["rule-neutral-reduplication"],
  },
  {
    id: "w-2",
    pinyin: "má",
    pinyinNumeric: "ma2",
    zhuyin: "ㄇㄚˊ",
    hanzi: "麻",
    meaning: "삼(베)",
    tone: 2,
    level: 1,
    category: "basics",
  },
  {
    id: "w-3",
    pinyin: "mǎ",
    pinyinNumeric: "ma3",
    zhuyin: "ㄇㄚˇ",
    hanzi: "马",
    meaning: "말(동물)",
    tone: 3,
    level: 1,
    category: "animals",
  },
  {
    id: "w-4",
    pinyin: "mà",
    pinyinNumeric: "ma4",
    zhuyin: "ㄇㄚˋ",
    hanzi: "骂",
    meaning: "욕하다/꾸짖다",
    tone: 4,
    level: 1,
    category: "verbs",
  },
  {
    id: "w-5",
    pinyin: "ma",
    pinyinNumeric: "ma5",
    zhuyin: "ㄇㄚ˙",
    hanzi: "吗",
    meaning: "의문 조사 (~입니까?)",
    tone: 5,
    level: 1,
    category: "grammar",
  },

  // 기초 인사 및 인칭 대명사
  {
    id: "w-6",
    pinyin: "nǐ",
    pinyinNumeric: "ni3",
    zhuyin: "ㄋㄧˇ",
    hanzi: "你",
    meaning: "너",
    tone: 3,
    level: 1,
    category: "pronouns",
    rules: ["rule-33", "rule-sandhi-33"],
  },
  {
    id: "w-7",
    pinyin: "hǎo",
    pinyinNumeric: "hao3",
    zhuyin: "ㄏㄠˇ",
    hanzi: "好",
    meaning: "좋다 / 안녕하다",
    tone: 3,
    level: 1,
    category: "adjectives",
    rules: ["rule-33", "rule-sandhi-33"],
  },
  {
    id: "w-8",
    pinyin: "wǒ",
    pinyinNumeric: "wo3",
    zhuyin: "ㄨㄛˇ",
    hanzi: "我",
    meaning: "나",
    tone: 3,
    level: 1,
    category: "pronouns",
    rules: ["rule-sandhi-333"],
  },
  {
    id: "w-9",
    pinyin: "tā",
    pinyinNumeric: "ta1",
    zhuyin: "ㄊㄚ",
    hanzi: "他",
    meaning: "그 (그 사람)",
    tone: 1,
    level: 1,
    category: "pronouns",
  },
  {
    id: "w-10",
    pinyin: "bù",
    pinyinNumeric: "bu4",
    zhuyin: "ㄅㄨˋ",
    hanzi: "不",
    meaning: "아니다 / ~않다",
    tone: 4,
    level: 1,
    category: "negation",
    rules: ["rule-bu", "rule-bu-4th", "rule-bu-neutral"],
  },
  {
    id: "w-11",
    pinyin: "shì",
    pinyinNumeric: "shi4",
    zhuyin: "ㄕˋ",
    hanzi: "是",
    meaning: "~이다",
    tone: 4,
    level: 1,
    category: "verbs",
    rules: ["rule-bu-4th"],
  },
  {
    id: "w-12",
    pinyin: "yī",
    pinyinNumeric: "yi1",
    zhuyin: "ㄧ",
    hanzi: "一",
    meaning: "하나 (1)",
    tone: 1,
    level: 1,
    category: "numbers",
    rules: ["rule-yi", "rule-yi-4th", "rule-yi-123"],
  },
  {
    id: "w-13",
    pinyin: "hěn",
    pinyinNumeric: "hen3",
    zhuyin: "ㄏㄣˇ",
    hanzi: "很",
    meaning: "매우 / 아주",
    tone: 3,
    level: 1,
    category: "adverbs",
    rules: ["rule-sandhi-333"],
  },
  {
    id: "w-14",
    pinyin: "xiè",
    pinyinNumeric: "xie4",
    zhuyin: "ㄒㄧㄝˋ",
    hanzi: "谢",
    meaning: "감사하다",
    tone: 4,
    level: 1,
    category: "greetings",
    rules: ["rule-neutral-reduplication"],
  },
  {
    id: "w-15",
    pinyin: "chī",
    pinyinNumeric: "chi1",
    zhuyin: "ㄔ",
    hanzi: "吃",
    meaning: "먹다",
    tone: 1,
    level: 1,
    category: "verbs",
  },
  {
    id: "w-16",
    pinyin: "hē",
    pinyinNumeric: "he1",
    zhuyin: "ㄏㄜ",
    hanzi: "喝",
    meaning: "마시다",
    tone: 1,
    level: 1,
    category: "verbs",
  },
  {
    id: "w-17",
    pinyin: "kàn",
    pinyinNumeric: "kan4",
    zhuyin: "ㄎㄢˋ",
    hanzi: "看",
    meaning: "보다 / 읽다",
    tone: 4,
    level: 1,
    category: "verbs",
  },
  {
    id: "w-18",
    pinyin: "qù",
    pinyinNumeric: "qu4",
    zhuyin: "ㄑㄩˋ",
    hanzi: "去",
    meaning: "가다",
    tone: 4,
    level: 1,
    category: "verbs",
  },
  {
    id: "w-19",
    pinyin: "lái",
    pinyinNumeric: "lai2",
    zhuyin: "ㄌㄞˊ",
    hanzi: "来",
    meaning: "오다",
    tone: 2,
    level: 1,
    category: "verbs",
  },
  {
    id: "w-20",
    pinyin: "yǒu",
    pinyinNumeric: "you3",
    zhuyin: "ㄧㄡˇ",
    hanzi: "有",
    meaning: "있다 / 소유하다",
    tone: 3,
    level: 1,
    category: "verbs",
  },
] as const;

